auto_scale_lr = dict(base_batch_size=16, enable=False)
backend_args = None
base_lr = 0.004
custom_hooks = [
    dict(
        ema_type='ExpMomentumEMA',
        momentum=0.0002,
        priority=49,
        type='EMAHook',
        update_buffers=True),
    dict(
        switch_epoch=280,
        switch_pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                keep_ratio=True,
                ratio_range=(
                    0.1,
                    2.0,
                ),
                scale=(
                    640,
                    640,
                ),
                type='RandomResize'),
            dict(crop_size=(
                640,
                640,
            ), type='RandomCrop'),
            dict(type='YOLOXHSVRandomAug'),
            dict(prob=0.5, type='RandomFlip'),
            dict(
                pad_val=dict(img=(
                    114,
                    114,
                    114,
                )),
                size=(
                    640,
                    640,
                ),
                type='Pad'),
            dict(type='PackDetInputs'),
        ],
        type='PipelineSwitchHook'),
]
data_root = '/content/dataset/'
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(interval=5, max_keep_ckpts=3, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='DetVisualizationHook'))
default_scope = 'mmdet'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
img_scales = [
    (
        640,
        640,
    ),
    (
        320,
        320,
    ),
    (
        960,
        960,
    ),
]
interval = 10
launcher = 'none'
load_from = 'rtmdet_m_8xb32-300e_coco_20220719_112220-229f527c.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
max_epochs = 300
model = dict(
    backbone=dict(
        act_cfg=dict(inplace=True, type='SiLU'),
        arch='P5',
        channel_attention=True,
        deepen_factor=0.67,
        expand_ratio=0.5,
        norm_cfg=dict(type='SyncBN'),
        type='CSPNeXt',
        widen_factor=0.75),
    bbox_head=dict(
        act_cfg=dict(inplace=True, type='SiLU'),
        anchor_generator=dict(
            offset=0, strides=[
                8,
                16,
                32,
            ], type='MlvlPointGenerator'),
        bbox_coder=dict(type='DistancePointBBoxCoder'),
        exp_on_reg=True,
        feat_channels=192,
        in_channels=192,
        loss_bbox=dict(loss_weight=2.0, type='GIoULoss'),
        loss_cls=dict(
            beta=2.0,
            loss_weight=1.0,
            type='QualityFocalLoss',
            use_sigmoid=True),
        norm_cfg=dict(type='SyncBN'),
        num_classes=609,
        pred_kernel_size=1,
        share_conv=True,
        stacked_convs=2,
        type='RTMDetSepBNHead',
        with_objectness=False),
    data_preprocessor=dict(
        batch_augments=None,
        bgr_to_rgb=False,
        mean=[
            103.53,
            116.28,
            123.675,
        ],
        std=[
            57.375,
            57.12,
            58.395,
        ],
        type='DetDataPreprocessor'),
    neck=dict(
        act_cfg=dict(inplace=True, type='SiLU'),
        expand_ratio=0.5,
        in_channels=[
            192,
            384,
            768,
        ],
        norm_cfg=dict(type='SyncBN'),
        num_csp_blocks=2,
        out_channels=192,
        type='CSPNeXtPAFPN'),
    test_cfg=dict(
        max_per_img=300,
        min_bbox_size=0,
        nms=dict(iou_threshold=0.65, type='nms'),
        nms_pre=30000,
        score_thr=0.001),
    train_cfg=dict(
        allowed_border=-1,
        assigner=dict(topk=13, type='DynamicSoftLabelAssigner'),
        debug=False,
        pos_weight=-1),
    type='RTMDet')
optim_wrapper = dict(
    loss_scale='dynamic',
    optimizer=dict(lr=0.003, type='AdamW', weight_decay=0.05),
    paramwise_cfg=dict(
        bias_decay_mult=0, bypass_duplicate=True, norm_decay_mult=0),
    type='AmpOptimWrapper')
param_scheduler = [
    dict(
        begin=0, by_epoch=False, end=1000, start_factor=0.001,
        type='LinearLR'),
    dict(
        T_max=50,
        begin=0,
        by_epoch=True,
        end=50,
        eta_min=0.00015000000000000001,
        type='CosineAnnealingLR'),
]
resume = False
stage2_num_epochs = 20
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=48,
    dataset=dict(
        ann_file='coco_annotations/test.json',
        backend_args=None,
        data_prefix=dict(img='Processed_Dataset_Pretrain/images/test/'),
        data_root='/content/dataset/',
        metainfo=dict(classes=[
            '2xist',
            '3D-GOLD',
            '4Skins',
            '66 North',
            '7-PE',
            '76',
            'A. Favre & Fils',
            'A.P.C',
            'AFuBeiBei',
            'AIMER',
            'AKOO',
            'AND1',
            'ANNICK GOUTAL',
            'ANTA',
            'AOKANG',
            'ASPINAL OF LONDON',
            'Abercrombie',
            'Abercrombie & Fitch',
            'Acne Studios',
            'Acqua Limone',
            'Addicted',
            'Adidas SB',
            'Admiral',
            'Adriatica',
            'Aerosoles',
            'Agacio',
            'Agnes b',
            'Ahnu',
            'Aigle',
            'Airness',
            'Akris',
            'Alain Figaret',
            'Alcatel-2',
            'Alchemist',
            'Alfani',
            'Alfred Dunhill',
            'Allen Edmonds',
            'Allrounder',
            'Alpina Watches',
            'Altra',
            'American Apparel',
            'American Eagle',
            'Andrew Christian',
            'Andrew Marc',
            'Anna Sui',
            'Anne Klein',
            'Antony Morato',
            'Aquascutum',
            'Aravon',
            "Arc'teryx",
            'Arcopedico',
            'Ariat',
            'Aristoc',
            'Aritzia',
            'Armani',
            'Armani Exchange',
            'Armani Junior',
            'Arri',
            'Athletic DNA',
            'Atletica',
            'Atticus',
            'Audemars Piguet',
            'Ayilian',
            'BALENO',
            'BOSE',
            'BUCO',
            'Baci Lingerie',
            'Badgley Mischka',
            'Baggallini',
            'Balenciaga',
            'Bally Shoe',
            'Balmain',
            'Barbie',
            'Barcode Berlin',
            'Bare Necessities',
            'Barneys New York',
            'Baume et Mercier-1',
            'Baume et Mercier-2',
            'Beach Bunny',
            'BeautiFeel',
            'BeiJiRong',
            'Bella Vita',
            'Ben Davis',
            'Berghaus',
            'Bestseller',
            'Betsey Johnson',
            'Betty Crocker',
            'Bill Blass',
            'Birkenstock',
            "Birki's",
            'Bjorn Borg',
            'Black Label Skateboards',
            'Black-eyed Pea',
            'Blondo',
            "Bloomingdale's",
            'Blundstone',
            'Bob Evans Restaurants',
            'Boboli',
            'Boconi',
            'Bomber',
            'Bonds',
            'Bonia',
            'Bootights',
            "Boscov's",
            'Bosideng',
            'Bostonian',
            'Bottega Veneta',
            'Boxfresh',
            'Breitling',
            'British Knights',
            'Bulgari',
            'Bulova',
            'Bunker',
            'Burlington Coat Factory',
            'C-IN2',
            'CDELALA',
            'Cacharel',
            'CaiBai',
            'Calvin Klein',
            'Calvin Klein Underwear',
            'Campmor',
            'Canada Goose',
            'Canterbury',
            'Capezio',
            'Captain Planet',
            'Carbrini',
            'Care Bears',
            'Carhartt',
            'Carlo Ferrara',
            'Casio',
            'Caslon',
            'Ceceba',
            'Celine',
            'Cesare Paciotti',
            'Chaco',
            'Champion',
            'Chipotle Mexican Grill-1',
            'Chipotle Mexican Grill-2',
            'Chippewa',
            'Chiquita',
            'Chloe',
            'Chooka',
            'Chopard',
            'Christian Lacroix',
            'Christian Louboutin',
            'Chrome Hearts',
            "Church's",
            'Churchkey Can',
            'Circa',
            'Ck Calvin Klein-1',
            'Ck Calvin Klein-2',
            'Clarks',
            'Cocksox',
            'Coldwater Creek',
            'Columbia',
            'Converse',
            'Covert',
            'Crumpler',
            'EKCO',
            'ERAL',
            'ERKE-1',
            'ERKE-2',
            'Earthies',
            'Easy Spirit',
            'Ecco',
            'Ecko Unltd',
            'Ed Hardy',
            'Eddie Bauer',
            'Eileen Fisher',
            'Elder-Beerman',
            'Ella Moss',
            'Ellesse',
            'Emerica',
            'Emilio',
            'Emilio Pucci',
            'Era',
            'Ergowear',
            'Ermanno Scervino',
            'Ermenegildo Zegna',
            'Errea',
            'Etnies',
            'Etro',
            'Everlast',
            'Excelsior',
            'Exofficio',
            'FUBU',
            'FUCT',
            'Faconnable',
            'Frank Dandy',
            'Frankie Morello',
            'Freegun',
            'French Connection',
            'French Sole',
            'Freya',
            'Frye',
            'Gabor',
            'Galvin Green',
            'Gap',
            'Geographics',
            'Georg Jensen',
            'Georgia Boot',
            'Gibson',
            'Giorgio',
            'Givova',
            'Glock-1',
            'Glock-2',
            'Golite',
            'Goya',
            'Grundies',
            'Guess',
            'Gul',
            'Guy Cotten',
            'Guy Laroche',
            'HBC',
            'HOM',
            'Haglofs',
            'Hammary',
            'Hanes',
            'Hanro',
            'Happy Socks',
            'Harry Winston-1',
            'Harry Winston-2',
            'Harvest Moon',
            'Head',
            'Heat-1',
            'Heat-2',
            'Heavy Eco',
            'Heckler & Koch',
            'Helsport',
            'Henri Wintermans',
            'Herschel Supply',
            'Hilleberg',
            'Hoka One One',
            'Hoya',
            'Hugo Boss',
            'Hummel-1',
            'Hummel-2',
            'Hurley International',
            'Hurley-1',
            'Hurley-2',
            'Hush Puppies',
            'INOHERB-2',
            'Imperial',
            'Independent Truck',
            'Injinji',
            'InterCall',
            'Intymen',
            'Invicta',
            'Isabel Maran-1',
            'Isabel Maran-2',
            'Izod',
            'JOULES',
            'Joe Fresh',
            'John Galliano',
            'John Richmond',
            'John Varvatos',
            'Joma-1',
            'Joma-2',
            'Josef Seibel',
            'KAIER',
            'KATE SPADE-1',
            'KATE SPADE-2',
            'KELA',
            'KaZhuMi',
            'Karhu',
            'Karl Kani-1',
            'Karl Kani-2',
            'Karl Lagerfeld',
            'Kathmandu',
            'Kavu',
            'Kelty',
            'Kenneth Cole',
            'Kenzo',
            'Kiton',
            'Knomo',
            'KooGa',
            'Kookai',
            'L.K.Bennett',
            'La Perla',
            'Los Angeles',
            'MARC BY MARC JACOBS',
            'MBT',
            "Man O' War",
            'Manhattan Portage',
            'adyson',
            'alpinestars-1',
            'alpinestars-2',
            'amnesia',
            'amy butler',
            'antonio',
            'atari 2600-1',
            'atari 2600-2',
            'aussieBum',
            'bobble',
            'brace yourself',
            'brine',
            'bukta',
            'cartelo',
            'chanel',
            'chaps',
            'charles owo',
            'charlotte olympia',
            'charlotte russe',
            'charming charlie',
            'chaya',
            'chilewich',
            'clement',
            'conlia',
            'corneliani',
            'eBags',
            'fox river mills',
            'garanimals',
            'gigo',
            'gumby',
            'gunnar',
            'habixiong',
            'he-man',
            'hubba wheels',
            'itg',
            'jianjiang',
            'jlindeberg-1',
            'jlindeberg-2',
            'kasumi',
            'kensie',
            'kookaburra',
            'krink',
            'l.l.bean',
            'la miu',
            'lacoste',
            'lang sha',
            'lanidor',
            'lesportsac',
            'levis',
            'loewe',
            'lonsdale',
            'looptworks',
            'loro piana',
            'louis vuitton-1',
            'louis vuitton-2',
            'luciano soprani',
            'lucky brand',
            'luminox',
            'luscious pink',
            'lyle',
            'maidenform',
            'majestic',
            'mandarina duck',
            'mansmiling',
            "marc o'polo",
            'marchesa',
            'marina rinaldi',
            'marni',
            'maui jim',
            'max mara',
            'maybach-1',
            'mephisto',
            'mesa boogie',
            'meters bonwe',
            'mexx',
            'meyba-1',
            'meyba-2',
            'mido',
            'minnetonka',
            'miss sixty',
            'missoni',
            'mitre',
            'miu miu',
            'moncler-1',
            'moncler-2',
            'montagu',
            'montane',
            'moonbasa',
            'mossimo',
            'mountain hardwear',
            'movado',
            'moving comfort-1',
            'moving comfort-2',
            'muchachomalo',
            'muzak-1',
            'muzak-2',
            'nanjiren',
            'naot',
            'napapijri',
            'nasty pig-1',
            'nasty pig-2',
            'naturalizer-1',
            'naturalizer-2',
            'new balance-1',
            'new balance-2',
            'new era',
            'nicole lee-1',
            'nicole lee-2',
            'nina ricci',
            'norrona',
            'obey',
            'old navy',
            'orient',
            'oriocx',
            'oris',
            'oroton',
            'orvis',
            'oryany',
            'osgoode marley',
            'osprey',
            'otto versand',
            'otz shoes',
            'ow lee',
            'oxxford',
            'pacsafe',
            'paddy pallin',
            'pajar',
            'panerai',
            'panoz',
            'patagonia',
            'patek philippe',
            'paul green',
            'pausa',
            'peace bird',
            'peak performance',
            'peebles',
            'pejo',
            'penalty',
            'penfield',
            'pepe jeans',
            'pequignet',
            'perlina',
            'petronor',
            'petzl',
            'pf flyers',
            'phat farm',
            'piado',
            'pierre cardin',
            'pikante',
            'ping',
            'pirma',
            'playboy',
            'polo ralph lauren',
            'pony',
            'prada',
            'propet',
            'pvh',
            'pythia',
            'qeelin',
            'qipai',
            'r & r collections',
            'r. m. williams',
            'rab',
            'rado',
            'rapha',
            'rare',
            'rax',
            'rebecca minkoff',
            'regatta',
            'regina',
            'relic',
            'reusch',
            'rieker',
            'rioni',
            'roamer',
            'robert allen',
            'roberto cavalli',
            'rochas',
            'rockport',
            'rocky',
            'rodania',
            'rolex',
            'royce leather',
            'ruans',
            'rudsak',
            'rvca',
            'ryb',
            'ryka',
            'sakroots',
            'saks fifth avenue',
            'salomon',
            'salvatore ferragamo',
            'samsonite',
            'sanita',
            'sansabelt',
            'sanuk',
            'satya paul',
            'saxx',
            'scarpa',
            'schiesser',
            'scotch and soda',
            'scottevest',
            'seafolly',
            'seagull',
            'seavees',
            'seiko',
            'septwolves',
            'sergio rossi',
            'sergio tacchini',
            'sergio valente',
            'seven fathoms',
            'shg',
            'shure',
            'simon',
            'simond',
            'sinaina',
            'sistema',
            'six deuce',
            'skins',
            'skiny',
            'skora',
            'smartwool',
            'smythson',
            'snow peak-2',
            'soffe',
            'sofft',
            'softspots',
            'sonia rykiel',
            'sophie paris',
            'sorel',
            'spanx',
            'sparco',
            'speedplay',
            'spenco',
            'sperry top-sider',
            'spiewak',
            'spring step',
            'sram',
            'stacy adams-1',
            'stacy adams-2',
            'star in the hood',
            'starbury-1',
            'starbury-2',
            'starter',
            'steve madden',
            'stowa',
            'strellson',
            'stussy',
            'sumdex',
            'supawear',
            'superfeet',
            'superga-1',
            'superga-2',
            'suunto',
            'swatch',
            'tarocash',
            'technomarine',
            'the flexx',
            'the north face',
            'the original muck boot company',
            'the timberland',
            'tiffany',
            'tiger of sweden',
            'tilted kilt',
            'timberland',
            'timbuk2-1',
            'timbuk2-2',
            'timex',
            'tissot',
            'titan industries',
            'titoni',
            'tom ford',
            'tom tailor',
            'tommy bahama',
            'tommy hilfiger',
            'topman',
            'trangoworld',
            'triumph-1',
            'triumph-2',
            'tudor',
            'tyr',
            'u.s. polo assn',
            'ugg australia',
            'under armour',
            'uniqlo',
            "valentino's",
            'vaneli',
            'vera bradley',
            'versace',
            'vibram',
            'viennois',
            'vince camuto-1',
            'vince camuto-2',
            'vionic',
            'vision street wear',
            'viso',
            'vivobarefoot-1',
            'vivobarefoot-2',
            'voit',
            'wesc',
            'whataburger-1',
            'whataburger-2',
            'wildcountry',
            'williams-sonoma',
            'wolford',
            'wolky',
            'wonderbra',
            'woolrich',
            'wrangler',
            'xoxo',
            'xtep',
            'yinshidai',
            'yishion',
            'yoko',
            'youngor-1',
            'youngor-2',
            'youngor-3',
            'yuzhaolin',
            'zara',
            'zaya',
            'zero halliburton',
            'zingara',
            'zino',
            'zodiac',
            'zoke',
        ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                640,
                640,
            ), type='Resize'),
            dict(
                pad_val=dict(img=(
                    114,
                    114,
                    114,
                )),
                size=(
                    640,
                    640,
                ),
                type='Pad'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=16,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='/content/dataset/coco_annotations/test.json',
    backend_args=None,
    classwise=False,
    format_only=False,
    metric='bbox',
    proposal_nums=(
        100,
        1,
        10,
    ),
    type='CocoMetric')
test_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(keep_ratio=True, scale=(
        640,
        640,
    ), type='Resize'),
    dict(pad_val=dict(img=(
        114,
        114,
        114,
    )), size=(
        640,
        640,
    ), type='Pad'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
        ),
        type='PackDetInputs'),
]
train_cfg = dict(
    dynamic_intervals=[
        (
            280,
            1,
        ),
    ],
    max_epochs=50,
    type='EpochBasedTrainLoop',
    val_interval=15)
train_dataloader = dict(
    batch_sampler=None,
    batch_size=48,
    dataset=dict(
        ann_file='coco_annotations/train.json',
        backend_args=None,
        data_prefix=dict(img='Processed_Dataset_Pretrain/images/train/'),
        data_root='/content/dataset/',
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        metainfo=dict(classes=[
            '2xist',
            '3D-GOLD',
            '4Skins',
            '66 North',
            '7-PE',
            '76',
            'A. Favre & Fils',
            'A.P.C',
            'AFuBeiBei',
            'AIMER',
            'AKOO',
            'AND1',
            'ANNICK GOUTAL',
            'ANTA',
            'AOKANG',
            'ASPINAL OF LONDON',
            'Abercrombie',
            'Abercrombie & Fitch',
            'Acne Studios',
            'Acqua Limone',
            'Addicted',
            'Adidas SB',
            'Admiral',
            'Adriatica',
            'Aerosoles',
            'Agacio',
            'Agnes b',
            'Ahnu',
            'Aigle',
            'Airness',
            'Akris',
            'Alain Figaret',
            'Alcatel-2',
            'Alchemist',
            'Alfani',
            'Alfred Dunhill',
            'Allen Edmonds',
            'Allrounder',
            'Alpina Watches',
            'Altra',
            'American Apparel',
            'American Eagle',
            'Andrew Christian',
            'Andrew Marc',
            'Anna Sui',
            'Anne Klein',
            'Antony Morato',
            'Aquascutum',
            'Aravon',
            "Arc'teryx",
            'Arcopedico',
            'Ariat',
            'Aristoc',
            'Aritzia',
            'Armani',
            'Armani Exchange',
            'Armani Junior',
            'Arri',
            'Athletic DNA',
            'Atletica',
            'Atticus',
            'Audemars Piguet',
            'Ayilian',
            'BALENO',
            'BOSE',
            'BUCO',
            'Baci Lingerie',
            'Badgley Mischka',
            'Baggallini',
            'Balenciaga',
            'Bally Shoe',
            'Balmain',
            'Barbie',
            'Barcode Berlin',
            'Bare Necessities',
            'Barneys New York',
            'Baume et Mercier-1',
            'Baume et Mercier-2',
            'Beach Bunny',
            'BeautiFeel',
            'BeiJiRong',
            'Bella Vita',
            'Ben Davis',
            'Berghaus',
            'Bestseller',
            'Betsey Johnson',
            'Betty Crocker',
            'Bill Blass',
            'Birkenstock',
            "Birki's",
            'Bjorn Borg',
            'Black Label Skateboards',
            'Black-eyed Pea',
            'Blondo',
            "Bloomingdale's",
            'Blundstone',
            'Bob Evans Restaurants',
            'Boboli',
            'Boconi',
            'Bomber',
            'Bonds',
            'Bonia',
            'Bootights',
            "Boscov's",
            'Bosideng',
            'Bostonian',
            'Bottega Veneta',
            'Boxfresh',
            'Breitling',
            'British Knights',
            'Bulgari',
            'Bulova',
            'Bunker',
            'Burlington Coat Factory',
            'C-IN2',
            'CDELALA',
            'Cacharel',
            'CaiBai',
            'Calvin Klein',
            'Calvin Klein Underwear',
            'Campmor',
            'Canada Goose',
            'Canterbury',
            'Capezio',
            'Captain Planet',
            'Carbrini',
            'Care Bears',
            'Carhartt',
            'Carlo Ferrara',
            'Casio',
            'Caslon',
            'Ceceba',
            'Celine',
            'Cesare Paciotti',
            'Chaco',
            'Champion',
            'Chipotle Mexican Grill-1',
            'Chipotle Mexican Grill-2',
            'Chippewa',
            'Chiquita',
            'Chloe',
            'Chooka',
            'Chopard',
            'Christian Lacroix',
            'Christian Louboutin',
            'Chrome Hearts',
            "Church's",
            'Churchkey Can',
            'Circa',
            'Ck Calvin Klein-1',
            'Ck Calvin Klein-2',
            'Clarks',
            'Cocksox',
            'Coldwater Creek',
            'Columbia',
            'Converse',
            'Covert',
            'Crumpler',
            'EKCO',
            'ERAL',
            'ERKE-1',
            'ERKE-2',
            'Earthies',
            'Easy Spirit',
            'Ecco',
            'Ecko Unltd',
            'Ed Hardy',
            'Eddie Bauer',
            'Eileen Fisher',
            'Elder-Beerman',
            'Ella Moss',
            'Ellesse',
            'Emerica',
            'Emilio',
            'Emilio Pucci',
            'Era',
            'Ergowear',
            'Ermanno Scervino',
            'Ermenegildo Zegna',
            'Errea',
            'Etnies',
            'Etro',
            'Everlast',
            'Excelsior',
            'Exofficio',
            'FUBU',
            'FUCT',
            'Faconnable',
            'Frank Dandy',
            'Frankie Morello',
            'Freegun',
            'French Connection',
            'French Sole',
            'Freya',
            'Frye',
            'Gabor',
            'Galvin Green',
            'Gap',
            'Geographics',
            'Georg Jensen',
            'Georgia Boot',
            'Gibson',
            'Giorgio',
            'Givova',
            'Glock-1',
            'Glock-2',
            'Golite',
            'Goya',
            'Grundies',
            'Guess',
            'Gul',
            'Guy Cotten',
            'Guy Laroche',
            'HBC',
            'HOM',
            'Haglofs',
            'Hammary',
            'Hanes',
            'Hanro',
            'Happy Socks',
            'Harry Winston-1',
            'Harry Winston-2',
            'Harvest Moon',
            'Head',
            'Heat-1',
            'Heat-2',
            'Heavy Eco',
            'Heckler & Koch',
            'Helsport',
            'Henri Wintermans',
            'Herschel Supply',
            'Hilleberg',
            'Hoka One One',
            'Hoya',
            'Hugo Boss',
            'Hummel-1',
            'Hummel-2',
            'Hurley International',
            'Hurley-1',
            'Hurley-2',
            'Hush Puppies',
            'INOHERB-2',
            'Imperial',
            'Independent Truck',
            'Injinji',
            'InterCall',
            'Intymen',
            'Invicta',
            'Isabel Maran-1',
            'Isabel Maran-2',
            'Izod',
            'JOULES',
            'Joe Fresh',
            'John Galliano',
            'John Richmond',
            'John Varvatos',
            'Joma-1',
            'Joma-2',
            'Josef Seibel',
            'KAIER',
            'KATE SPADE-1',
            'KATE SPADE-2',
            'KELA',
            'KaZhuMi',
            'Karhu',
            'Karl Kani-1',
            'Karl Kani-2',
            'Karl Lagerfeld',
            'Kathmandu',
            'Kavu',
            'Kelty',
            'Kenneth Cole',
            'Kenzo',
            'Kiton',
            'Knomo',
            'KooGa',
            'Kookai',
            'L.K.Bennett',
            'La Perla',
            'Los Angeles',
            'MARC BY MARC JACOBS',
            'MBT',
            "Man O' War",
            'Manhattan Portage',
            'adyson',
            'alpinestars-1',
            'alpinestars-2',
            'amnesia',
            'amy butler',
            'antonio',
            'atari 2600-1',
            'atari 2600-2',
            'aussieBum',
            'bobble',
            'brace yourself',
            'brine',
            'bukta',
            'cartelo',
            'chanel',
            'chaps',
            'charles owo',
            'charlotte olympia',
            'charlotte russe',
            'charming charlie',
            'chaya',
            'chilewich',
            'clement',
            'conlia',
            'corneliani',
            'eBags',
            'fox river mills',
            'garanimals',
            'gigo',
            'gumby',
            'gunnar',
            'habixiong',
            'he-man',
            'hubba wheels',
            'itg',
            'jianjiang',
            'jlindeberg-1',
            'jlindeberg-2',
            'kasumi',
            'kensie',
            'kookaburra',
            'krink',
            'l.l.bean',
            'la miu',
            'lacoste',
            'lang sha',
            'lanidor',
            'lesportsac',
            'levis',
            'loewe',
            'lonsdale',
            'looptworks',
            'loro piana',
            'louis vuitton-1',
            'louis vuitton-2',
            'luciano soprani',
            'lucky brand',
            'luminox',
            'luscious pink',
            'lyle',
            'maidenform',
            'majestic',
            'mandarina duck',
            'mansmiling',
            "marc o'polo",
            'marchesa',
            'marina rinaldi',
            'marni',
            'maui jim',
            'max mara',
            'maybach-1',
            'mephisto',
            'mesa boogie',
            'meters bonwe',
            'mexx',
            'meyba-1',
            'meyba-2',
            'mido',
            'minnetonka',
            'miss sixty',
            'missoni',
            'mitre',
            'miu miu',
            'moncler-1',
            'moncler-2',
            'montagu',
            'montane',
            'moonbasa',
            'mossimo',
            'mountain hardwear',
            'movado',
            'moving comfort-1',
            'moving comfort-2',
            'muchachomalo',
            'muzak-1',
            'muzak-2',
            'nanjiren',
            'naot',
            'napapijri',
            'nasty pig-1',
            'nasty pig-2',
            'naturalizer-1',
            'naturalizer-2',
            'new balance-1',
            'new balance-2',
            'new era',
            'nicole lee-1',
            'nicole lee-2',
            'nina ricci',
            'norrona',
            'obey',
            'old navy',
            'orient',
            'oriocx',
            'oris',
            'oroton',
            'orvis',
            'oryany',
            'osgoode marley',
            'osprey',
            'otto versand',
            'otz shoes',
            'ow lee',
            'oxxford',
            'pacsafe',
            'paddy pallin',
            'pajar',
            'panerai',
            'panoz',
            'patagonia',
            'patek philippe',
            'paul green',
            'pausa',
            'peace bird',
            'peak performance',
            'peebles',
            'pejo',
            'penalty',
            'penfield',
            'pepe jeans',
            'pequignet',
            'perlina',
            'petronor',
            'petzl',
            'pf flyers',
            'phat farm',
            'piado',
            'pierre cardin',
            'pikante',
            'ping',
            'pirma',
            'playboy',
            'polo ralph lauren',
            'pony',
            'prada',
            'propet',
            'pvh',
            'pythia',
            'qeelin',
            'qipai',
            'r & r collections',
            'r. m. williams',
            'rab',
            'rado',
            'rapha',
            'rare',
            'rax',
            'rebecca minkoff',
            'regatta',
            'regina',
            'relic',
            'reusch',
            'rieker',
            'rioni',
            'roamer',
            'robert allen',
            'roberto cavalli',
            'rochas',
            'rockport',
            'rocky',
            'rodania',
            'rolex',
            'royce leather',
            'ruans',
            'rudsak',
            'rvca',
            'ryb',
            'ryka',
            'sakroots',
            'saks fifth avenue',
            'salomon',
            'salvatore ferragamo',
            'samsonite',
            'sanita',
            'sansabelt',
            'sanuk',
            'satya paul',
            'saxx',
            'scarpa',
            'schiesser',
            'scotch and soda',
            'scottevest',
            'seafolly',
            'seagull',
            'seavees',
            'seiko',
            'septwolves',
            'sergio rossi',
            'sergio tacchini',
            'sergio valente',
            'seven fathoms',
            'shg',
            'shure',
            'simon',
            'simond',
            'sinaina',
            'sistema',
            'six deuce',
            'skins',
            'skiny',
            'skora',
            'smartwool',
            'smythson',
            'snow peak-2',
            'soffe',
            'sofft',
            'softspots',
            'sonia rykiel',
            'sophie paris',
            'sorel',
            'spanx',
            'sparco',
            'speedplay',
            'spenco',
            'sperry top-sider',
            'spiewak',
            'spring step',
            'sram',
            'stacy adams-1',
            'stacy adams-2',
            'star in the hood',
            'starbury-1',
            'starbury-2',
            'starter',
            'steve madden',
            'stowa',
            'strellson',
            'stussy',
            'sumdex',
            'supawear',
            'superfeet',
            'superga-1',
            'superga-2',
            'suunto',
            'swatch',
            'tarocash',
            'technomarine',
            'the flexx',
            'the north face',
            'the original muck boot company',
            'the timberland',
            'tiffany',
            'tiger of sweden',
            'tilted kilt',
            'timberland',
            'timbuk2-1',
            'timbuk2-2',
            'timex',
            'tissot',
            'titan industries',
            'titoni',
            'tom ford',
            'tom tailor',
            'tommy bahama',
            'tommy hilfiger',
            'topman',
            'trangoworld',
            'triumph-1',
            'triumph-2',
            'tudor',
            'tyr',
            'u.s. polo assn',
            'ugg australia',
            'under armour',
            'uniqlo',
            "valentino's",
            'vaneli',
            'vera bradley',
            'versace',
            'vibram',
            'viennois',
            'vince camuto-1',
            'vince camuto-2',
            'vionic',
            'vision street wear',
            'viso',
            'vivobarefoot-1',
            'vivobarefoot-2',
            'voit',
            'wesc',
            'whataburger-1',
            'whataburger-2',
            'wildcountry',
            'williams-sonoma',
            'wolford',
            'wolky',
            'wonderbra',
            'woolrich',
            'wrangler',
            'xoxo',
            'xtep',
            'yinshidai',
            'yishion',
            'yoko',
            'youngor-1',
            'youngor-2',
            'youngor-3',
            'yuzhaolin',
            'zara',
            'zaya',
            'zero halliburton',
            'zingara',
            'zino',
            'zodiac',
            'zoke',
        ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(img_scale=(
                640,
                640,
            ), pad_val=114.0, type='CachedMosaic'),
            dict(
                keep_ratio=True,
                ratio_range=(
                    0.1,
                    2.0,
                ),
                scale=(
                    1280,
                    1280,
                ),
                type='RandomResize'),
            dict(crop_size=(
                640,
                640,
            ), type='RandomCrop'),
            dict(type='YOLOXHSVRandomAug'),
            dict(prob=0.5, type='RandomFlip'),
            dict(
                pad_val=dict(img=(
                    114,
                    114,
                    114,
                )),
                size=(
                    640,
                    640,
                ),
                type='Pad'),
            dict(
                img_scale=(
                    640,
                    640,
                ),
                max_cached_images=20,
                pad_val=(
                    114,
                    114,
                    114,
                ),
                ratio_range=(
                    1.0,
                    1.0,
                ),
                type='CachedMixUp'),
            dict(type='PackDetInputs'),
        ],
        type='CocoDataset'),
    num_workers=16,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(img_scale=(
        640,
        640,
    ), pad_val=114.0, type='CachedMosaic'),
    dict(
        keep_ratio=True,
        ratio_range=(
            0.1,
            2.0,
        ),
        scale=(
            1280,
            1280,
        ),
        type='RandomResize'),
    dict(crop_size=(
        640,
        640,
    ), type='RandomCrop'),
    dict(type='YOLOXHSVRandomAug'),
    dict(prob=0.5, type='RandomFlip'),
    dict(pad_val=dict(img=(
        114,
        114,
        114,
    )), size=(
        640,
        640,
    ), type='Pad'),
    dict(
        img_scale=(
            640,
            640,
        ),
        max_cached_images=20,
        pad_val=(
            114,
            114,
            114,
        ),
        ratio_range=(
            1.0,
            1.0,
        ),
        type='CachedMixUp'),
    dict(type='PackDetInputs'),
]
train_pipeline_stage2 = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        keep_ratio=True,
        ratio_range=(
            0.1,
            2.0,
        ),
        scale=(
            640,
            640,
        ),
        type='RandomResize'),
    dict(crop_size=(
        640,
        640,
    ), type='RandomCrop'),
    dict(type='YOLOXHSVRandomAug'),
    dict(prob=0.5, type='RandomFlip'),
    dict(pad_val=dict(img=(
        114,
        114,
        114,
    )), size=(
        640,
        640,
    ), type='Pad'),
    dict(type='PackDetInputs'),
]
tta_model = dict(
    tta_cfg=dict(max_per_img=100, nms=dict(iou_threshold=0.6, type='nms')),
    type='DetTTAModel')
tta_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(
        transforms=[
            [
                dict(keep_ratio=True, scale=(
                    640,
                    640,
                ), type='Resize'),
                dict(keep_ratio=True, scale=(
                    320,
                    320,
                ), type='Resize'),
                dict(keep_ratio=True, scale=(
                    960,
                    960,
                ), type='Resize'),
            ],
            [
                dict(prob=1.0, type='RandomFlip'),
                dict(prob=0.0, type='RandomFlip'),
            ],
            [
                dict(
                    pad_val=dict(img=(
                        114,
                        114,
                        114,
                    )),
                    size=(
                        960,
                        960,
                    ),
                    type='Pad'),
            ],
            [
                dict(type='LoadAnnotations', with_bbox=True),
            ],
            [
                dict(
                    meta_keys=(
                        'img_id',
                        'img_path',
                        'ori_shape',
                        'img_shape',
                        'scale_factor',
                        'flip',
                        'flip_direction',
                    ),
                    type='PackDetInputs'),
            ],
        ],
        type='TestTimeAug'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=48,
    dataset=dict(
        ann_file='coco_annotations/val.json',
        backend_args=None,
        data_prefix=dict(img='Processed_Dataset_Pretrain/images/val/'),
        data_root='/content/dataset/',
        metainfo=dict(classes=[
            '2xist',
            '3D-GOLD',
            '4Skins',
            '66 North',
            '7-PE',
            '76',
            'A. Favre & Fils',
            'A.P.C',
            'AFuBeiBei',
            'AIMER',
            'AKOO',
            'AND1',
            'ANNICK GOUTAL',
            'ANTA',
            'AOKANG',
            'ASPINAL OF LONDON',
            'Abercrombie',
            'Abercrombie & Fitch',
            'Acne Studios',
            'Acqua Limone',
            'Addicted',
            'Adidas SB',
            'Admiral',
            'Adriatica',
            'Aerosoles',
            'Agacio',
            'Agnes b',
            'Ahnu',
            'Aigle',
            'Airness',
            'Akris',
            'Alain Figaret',
            'Alcatel-2',
            'Alchemist',
            'Alfani',
            'Alfred Dunhill',
            'Allen Edmonds',
            'Allrounder',
            'Alpina Watches',
            'Altra',
            'American Apparel',
            'American Eagle',
            'Andrew Christian',
            'Andrew Marc',
            'Anna Sui',
            'Anne Klein',
            'Antony Morato',
            'Aquascutum',
            'Aravon',
            "Arc'teryx",
            'Arcopedico',
            'Ariat',
            'Aristoc',
            'Aritzia',
            'Armani',
            'Armani Exchange',
            'Armani Junior',
            'Arri',
            'Athletic DNA',
            'Atletica',
            'Atticus',
            'Audemars Piguet',
            'Ayilian',
            'BALENO',
            'BOSE',
            'BUCO',
            'Baci Lingerie',
            'Badgley Mischka',
            'Baggallini',
            'Balenciaga',
            'Bally Shoe',
            'Balmain',
            'Barbie',
            'Barcode Berlin',
            'Bare Necessities',
            'Barneys New York',
            'Baume et Mercier-1',
            'Baume et Mercier-2',
            'Beach Bunny',
            'BeautiFeel',
            'BeiJiRong',
            'Bella Vita',
            'Ben Davis',
            'Berghaus',
            'Bestseller',
            'Betsey Johnson',
            'Betty Crocker',
            'Bill Blass',
            'Birkenstock',
            "Birki's",
            'Bjorn Borg',
            'Black Label Skateboards',
            'Black-eyed Pea',
            'Blondo',
            "Bloomingdale's",
            'Blundstone',
            'Bob Evans Restaurants',
            'Boboli',
            'Boconi',
            'Bomber',
            'Bonds',
            'Bonia',
            'Bootights',
            "Boscov's",
            'Bosideng',
            'Bostonian',
            'Bottega Veneta',
            'Boxfresh',
            'Breitling',
            'British Knights',
            'Bulgari',
            'Bulova',
            'Bunker',
            'Burlington Coat Factory',
            'C-IN2',
            'CDELALA',
            'Cacharel',
            'CaiBai',
            'Calvin Klein',
            'Calvin Klein Underwear',
            'Campmor',
            'Canada Goose',
            'Canterbury',
            'Capezio',
            'Captain Planet',
            'Carbrini',
            'Care Bears',
            'Carhartt',
            'Carlo Ferrara',
            'Casio',
            'Caslon',
            'Ceceba',
            'Celine',
            'Cesare Paciotti',
            'Chaco',
            'Champion',
            'Chipotle Mexican Grill-1',
            'Chipotle Mexican Grill-2',
            'Chippewa',
            'Chiquita',
            'Chloe',
            'Chooka',
            'Chopard',
            'Christian Lacroix',
            'Christian Louboutin',
            'Chrome Hearts',
            "Church's",
            'Churchkey Can',
            'Circa',
            'Ck Calvin Klein-1',
            'Ck Calvin Klein-2',
            'Clarks',
            'Cocksox',
            'Coldwater Creek',
            'Columbia',
            'Converse',
            'Covert',
            'Crumpler',
            'EKCO',
            'ERAL',
            'ERKE-1',
            'ERKE-2',
            'Earthies',
            'Easy Spirit',
            'Ecco',
            'Ecko Unltd',
            'Ed Hardy',
            'Eddie Bauer',
            'Eileen Fisher',
            'Elder-Beerman',
            'Ella Moss',
            'Ellesse',
            'Emerica',
            'Emilio',
            'Emilio Pucci',
            'Era',
            'Ergowear',
            'Ermanno Scervino',
            'Ermenegildo Zegna',
            'Errea',
            'Etnies',
            'Etro',
            'Everlast',
            'Excelsior',
            'Exofficio',
            'FUBU',
            'FUCT',
            'Faconnable',
            'Frank Dandy',
            'Frankie Morello',
            'Freegun',
            'French Connection',
            'French Sole',
            'Freya',
            'Frye',
            'Gabor',
            'Galvin Green',
            'Gap',
            'Geographics',
            'Georg Jensen',
            'Georgia Boot',
            'Gibson',
            'Giorgio',
            'Givova',
            'Glock-1',
            'Glock-2',
            'Golite',
            'Goya',
            'Grundies',
            'Guess',
            'Gul',
            'Guy Cotten',
            'Guy Laroche',
            'HBC',
            'HOM',
            'Haglofs',
            'Hammary',
            'Hanes',
            'Hanro',
            'Happy Socks',
            'Harry Winston-1',
            'Harry Winston-2',
            'Harvest Moon',
            'Head',
            'Heat-1',
            'Heat-2',
            'Heavy Eco',
            'Heckler & Koch',
            'Helsport',
            'Henri Wintermans',
            'Herschel Supply',
            'Hilleberg',
            'Hoka One One',
            'Hoya',
            'Hugo Boss',
            'Hummel-1',
            'Hummel-2',
            'Hurley International',
            'Hurley-1',
            'Hurley-2',
            'Hush Puppies',
            'INOHERB-2',
            'Imperial',
            'Independent Truck',
            'Injinji',
            'InterCall',
            'Intymen',
            'Invicta',
            'Isabel Maran-1',
            'Isabel Maran-2',
            'Izod',
            'JOULES',
            'Joe Fresh',
            'John Galliano',
            'John Richmond',
            'John Varvatos',
            'Joma-1',
            'Joma-2',
            'Josef Seibel',
            'KAIER',
            'KATE SPADE-1',
            'KATE SPADE-2',
            'KELA',
            'KaZhuMi',
            'Karhu',
            'Karl Kani-1',
            'Karl Kani-2',
            'Karl Lagerfeld',
            'Kathmandu',
            'Kavu',
            'Kelty',
            'Kenneth Cole',
            'Kenzo',
            'Kiton',
            'Knomo',
            'KooGa',
            'Kookai',
            'L.K.Bennett',
            'La Perla',
            'Los Angeles',
            'MARC BY MARC JACOBS',
            'MBT',
            "Man O' War",
            'Manhattan Portage',
            'adyson',
            'alpinestars-1',
            'alpinestars-2',
            'amnesia',
            'amy butler',
            'antonio',
            'atari 2600-1',
            'atari 2600-2',
            'aussieBum',
            'bobble',
            'brace yourself',
            'brine',
            'bukta',
            'cartelo',
            'chanel',
            'chaps',
            'charles owo',
            'charlotte olympia',
            'charlotte russe',
            'charming charlie',
            'chaya',
            'chilewich',
            'clement',
            'conlia',
            'corneliani',
            'eBags',
            'fox river mills',
            'garanimals',
            'gigo',
            'gumby',
            'gunnar',
            'habixiong',
            'he-man',
            'hubba wheels',
            'itg',
            'jianjiang',
            'jlindeberg-1',
            'jlindeberg-2',
            'kasumi',
            'kensie',
            'kookaburra',
            'krink',
            'l.l.bean',
            'la miu',
            'lacoste',
            'lang sha',
            'lanidor',
            'lesportsac',
            'levis',
            'loewe',
            'lonsdale',
            'looptworks',
            'loro piana',
            'louis vuitton-1',
            'louis vuitton-2',
            'luciano soprani',
            'lucky brand',
            'luminox',
            'luscious pink',
            'lyle',
            'maidenform',
            'majestic',
            'mandarina duck',
            'mansmiling',
            "marc o'polo",
            'marchesa',
            'marina rinaldi',
            'marni',
            'maui jim',
            'max mara',
            'maybach-1',
            'mephisto',
            'mesa boogie',
            'meters bonwe',
            'mexx',
            'meyba-1',
            'meyba-2',
            'mido',
            'minnetonka',
            'miss sixty',
            'missoni',
            'mitre',
            'miu miu',
            'moncler-1',
            'moncler-2',
            'montagu',
            'montane',
            'moonbasa',
            'mossimo',
            'mountain hardwear',
            'movado',
            'moving comfort-1',
            'moving comfort-2',
            'muchachomalo',
            'muzak-1',
            'muzak-2',
            'nanjiren',
            'naot',
            'napapijri',
            'nasty pig-1',
            'nasty pig-2',
            'naturalizer-1',
            'naturalizer-2',
            'new balance-1',
            'new balance-2',
            'new era',
            'nicole lee-1',
            'nicole lee-2',
            'nina ricci',
            'norrona',
            'obey',
            'old navy',
            'orient',
            'oriocx',
            'oris',
            'oroton',
            'orvis',
            'oryany',
            'osgoode marley',
            'osprey',
            'otto versand',
            'otz shoes',
            'ow lee',
            'oxxford',
            'pacsafe',
            'paddy pallin',
            'pajar',
            'panerai',
            'panoz',
            'patagonia',
            'patek philippe',
            'paul green',
            'pausa',
            'peace bird',
            'peak performance',
            'peebles',
            'pejo',
            'penalty',
            'penfield',
            'pepe jeans',
            'pequignet',
            'perlina',
            'petronor',
            'petzl',
            'pf flyers',
            'phat farm',
            'piado',
            'pierre cardin',
            'pikante',
            'ping',
            'pirma',
            'playboy',
            'polo ralph lauren',
            'pony',
            'prada',
            'propet',
            'pvh',
            'pythia',
            'qeelin',
            'qipai',
            'r & r collections',
            'r. m. williams',
            'rab',
            'rado',
            'rapha',
            'rare',
            'rax',
            'rebecca minkoff',
            'regatta',
            'regina',
            'relic',
            'reusch',
            'rieker',
            'rioni',
            'roamer',
            'robert allen',
            'roberto cavalli',
            'rochas',
            'rockport',
            'rocky',
            'rodania',
            'rolex',
            'royce leather',
            'ruans',
            'rudsak',
            'rvca',
            'ryb',
            'ryka',
            'sakroots',
            'saks fifth avenue',
            'salomon',
            'salvatore ferragamo',
            'samsonite',
            'sanita',
            'sansabelt',
            'sanuk',
            'satya paul',
            'saxx',
            'scarpa',
            'schiesser',
            'scotch and soda',
            'scottevest',
            'seafolly',
            'seagull',
            'seavees',
            'seiko',
            'septwolves',
            'sergio rossi',
            'sergio tacchini',
            'sergio valente',
            'seven fathoms',
            'shg',
            'shure',
            'simon',
            'simond',
            'sinaina',
            'sistema',
            'six deuce',
            'skins',
            'skiny',
            'skora',
            'smartwool',
            'smythson',
            'snow peak-2',
            'soffe',
            'sofft',
            'softspots',
            'sonia rykiel',
            'sophie paris',
            'sorel',
            'spanx',
            'sparco',
            'speedplay',
            'spenco',
            'sperry top-sider',
            'spiewak',
            'spring step',
            'sram',
            'stacy adams-1',
            'stacy adams-2',
            'star in the hood',
            'starbury-1',
            'starbury-2',
            'starter',
            'steve madden',
            'stowa',
            'strellson',
            'stussy',
            'sumdex',
            'supawear',
            'superfeet',
            'superga-1',
            'superga-2',
            'suunto',
            'swatch',
            'tarocash',
            'technomarine',
            'the flexx',
            'the north face',
            'the original muck boot company',
            'the timberland',
            'tiffany',
            'tiger of sweden',
            'tilted kilt',
            'timberland',
            'timbuk2-1',
            'timbuk2-2',
            'timex',
            'tissot',
            'titan industries',
            'titoni',
            'tom ford',
            'tom tailor',
            'tommy bahama',
            'tommy hilfiger',
            'topman',
            'trangoworld',
            'triumph-1',
            'triumph-2',
            'tudor',
            'tyr',
            'u.s. polo assn',
            'ugg australia',
            'under armour',
            'uniqlo',
            "valentino's",
            'vaneli',
            'vera bradley',
            'versace',
            'vibram',
            'viennois',
            'vince camuto-1',
            'vince camuto-2',
            'vionic',
            'vision street wear',
            'viso',
            'vivobarefoot-1',
            'vivobarefoot-2',
            'voit',
            'wesc',
            'whataburger-1',
            'whataburger-2',
            'wildcountry',
            'williams-sonoma',
            'wolford',
            'wolky',
            'wonderbra',
            'woolrich',
            'wrangler',
            'xoxo',
            'xtep',
            'yinshidai',
            'yishion',
            'yoko',
            'youngor-1',
            'youngor-2',
            'youngor-3',
            'yuzhaolin',
            'zara',
            'zaya',
            'zero halliburton',
            'zingara',
            'zino',
            'zodiac',
            'zoke',
        ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                640,
                640,
            ), type='Resize'),
            dict(
                pad_val=dict(img=(
                    114,
                    114,
                    114,
                )),
                size=(
                    640,
                    640,
                ),
                type='Pad'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=16,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='/content/dataset/coco_annotations/val.json',
    backend_args=None,
    classwise=False,
    format_only=False,
    metric='bbox',
    proposal_nums=(
        100,
        1,
        10,
    ),
    type='CocoMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
        dict(
            init_kwargs=dict(
                name='rtmdet-m-a100-Batch48-Safe',
                project='rtmdet-logo-609cls'),
            type='WandbVisBackend'),
    ])
work_dir = './rtmdet_m_logo_609cls_batch48'
